feat: add fuzzy text search support
ParthJadhav/rust_search pull request #5
Opened 2022-10-30 09:15 UTC by ParthJadhav

2022-10-30 09:38 UTC, TheAwiteb requested changes

2022-10-30 09:38 UTC, TheAwiteb commented on src/lib.rs
> +        strict: Option<bool>,
This should be `bool` not `Option<bool>`

2022-10-30 10:17 UTC, TheAwiteb commented
Hey @ParthJadhav, don't release this PR, because it and #6 have a BC, so release both in one major version

2022-10-30 16:10 UTC, ParthJadhav commented
Alright cool.

2022-10-30 19:15 UTC, TheAwiteb commented
@ParthJadhav there is no strict when search without extinction, i think it's better not to have strict with the extension too, do you think?

2022-11-05 07:29 UTC, ParthJadhav commented
@TheAwiteb added this feature to below PR. 
https://github.com/ParthJadhav/rust_search/pull/9

> @ParthJadhav there is no strict when search without extinction, i think it's better not to have strict with the extension too, do you think?

Yes, It defaults to be `not strict` when passed `None`

2022-11-05 07:30 UTC, closed without merging